apiVersion: v1
kind: Service
metadata:
  name:  mcan97-rtp-service
  namespace: mcan97
spec:
  type: NodePort
  selector:
    app: mcan97-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
